### PR TITLE
Added functions conjuction

### PR DESCRIPTION
**Pull request by bgaifullin**
Simple syntax for functions conjunction
the result if function which before '|>' will be added as last argument to function which is after '|>'

```go
"foo() |> bar(10) |> woo(20)
// it is same as
"woo(20, bar(10, foo()))"
```

### CODE REVIEW

**Comment by bgaifullin** [comment]
@Knetic Please share your opinion, how this can be done in right way. I will rework.

**Comment by yeka** [comment]
Why do you need `|>` while `"woo(20, bar(10, foo()))"` works?

**Comment by bgaifullin** [comment]
It is just syntax sugar and more convenient way to declare big pipeline which contains 10+functions.
Are you agree that
x1() |> x2() |> ... |> xN() is more readable than
x1(x2(x3(...(xN())...))) . And it is without function arguments.

**Comment by bgaifullin** [comment]
BTW: the go template library uses the same approach:
https://golang.org/pkg/text/template/#hdr-Pipelines

> A pipeline may be "chained" by separating a sequence of commands with pipeline characters '|'. In a chained pipeline, the result of each command is passed as the last argument of the following command. The output of the final command in the pipeline is the value of the pipeline.

**Comment by Knetic** [comment]
I can agree that some people may prefer conjunction, but I generally try to keep syntax sugar out of this library. Personally, I find it easier to reason about code if there are fewer syntactic ways to express an operation. 

I do appreciate the time put into this PR, but I don't think i can accept. :disappointed:

**Pull request closed without merging**
